; ============================================================================
; cycloidgen - Windows installer
;
;   pyinstaller cycloidgen.spec --noconfirm     (writes dist\cycloidgen)
;   makensis packaging\cycloidgen.nsi           (writes releases\...Setup.exe)
;
; or run packaging\release.ps1, which does both and checks the order.
; ============================================================================

!define APP_NAME    "cycloidgen"
!define APP_VENDOR  "Medinstech"
!define APP_WEBSITE "https://github.com/medinstech/cycloidgen"
!define APP_HELPURL "https://github.com/medinstech/cycloidgen/issues"
!define EXE_NAME    "cycloidgen.exe"

; NSIS resolves the file arguments of its own directives - !searchparse,
; LicenseData, MUI_ICON, File - against the directory holding the *script*, not
; against wherever makensis was invoked from.  So the repository root is one
; level up from here, spelled relatively.  The preprocessor's `!if /FileExists`
; is the exception and wants ${__FILEDIR__}; both appear below.
!define ROOT ".."

; Overridable so that CI can compile this script against a stub folder.  That
; check takes seconds and catches a broken page order or a missing string long
; before anyone waits half an hour for the real bundle to compress.
!ifndef BUILD_DIR
  !define BUILD_DIR "${ROOT}\dist\cycloidgen"
!endif

; The version comes out of the one line that carries it - see RELEASING.md.
; A text match, so the format of that line is a contract; tests/test_version.py
; holds both ends of it.
!searchparse /file "${ROOT}\cycloidgen\__init__.py" `__version__ = "` APP_VERSION `"`

!define SETUP_NAME "cycloidgen_v${APP_VERSION}_Setup.exe"

; The bundle is around 1.2 GB, essentially all OCCT, and LZMA on that takes a
; while.  FASTPACK (release.ps1 -FastPack) swaps in zlib for internal test
; builds only: roughly four times faster to pack and a much larger installer.
!ifdef FASTPACK
  SetCompressor /SOLID zlib
!else
  SetCompressor /SOLID lzma
  SetCompressorDictSize 64
!endif

!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"

; ----------------------------------------------------------------- system --
Name "${APP_NAME} ${APP_VERSION}"
OutFile "${ROOT}\releases\${SETUP_NAME}"
BrandingText "${APP_VENDOR}  -  ${APP_NAME} ${APP_VERSION}"
InstallDir "$PROGRAMFILES64\${APP_NAME}"
InstallDirRegKey HKLM "Software\${APP_VENDOR}\${APP_NAME}" "Install_Dir"
RequestExecutionLevel admin
Unicode true

; VIProductVersion wants exactly four integers and the project version has
; three, so the build field is a constant zero.  The human-readable strings
; below carry the real version, including any pre-release suffix.
VIProductVersion "${APP_VERSION}.0"
VIAddVersionKey "ProductName" "${APP_NAME}"
VIAddVersionKey "CompanyName" "${APP_VENDOR}"
VIAddVersionKey "LegalCopyright" "Copyright 2026 ${APP_VENDOR}. Apache-2.0."
VIAddVersionKey "FileDescription" "${APP_NAME} Setup"
VIAddVersionKey "FileVersion" "${APP_VERSION}"
VIAddVersionKey "ProductVersion" "${APP_VERSION}"

; ------------------------------------------------------------------- look --
!define MUI_ABORTWARNING
!define MUI_ABORTWARNING_TEXT "$(S_AbortWarn)"

!if /FileExists "${ROOT}\cycloidgen\ui\assets\cycloidgen.ico"
  !define MUI_ICON   "${ROOT}\cycloidgen\ui\assets\cycloidgen.ico"
  !define MUI_UNICON "${ROOT}\cycloidgen\ui\assets\cycloidgen.ico"
!endif

; Generated by `python tools/make_setup_graphics.py` from the committed brand
; assets, and committed in turn, so makensis needs no Python.  The sizes are
; MUI2's fixed control dimensions: header 150x57, wizard 164x314, 24-bit BMP.
; Guarded on existence so the script still builds in a checkout without them.
!if /FileExists "${__FILEDIR__}\setup_graphics\header.bmp"
  !define MUI_HEADERIMAGE
  !define MUI_HEADERIMAGE_BITMAP "setup_graphics\header.bmp"
  !define MUI_HEADERIMAGE_RIGHT
!endif
!if /FileExists "${__FILEDIR__}\setup_graphics\wizard.bmp"
  !define MUI_WELCOMEFINISHPAGE_BITMAP   "setup_graphics\wizard.bmp"
  !define MUI_UNWELCOMEFINISHPAGE_BITMAP "setup_graphics\wizard.bmp"
!endif

; The brand paper, which is what the bitmaps fade into - the application's own
; light surface rather than white.  Deliberately *not* a dark wizard: NSIS
; cannot set the text colour of the license box, the component list or the
; directory field, so a dark background there leaves black text on black.
!define MUI_BGCOLOR "F6F5FF"
!define MUI_COMPONENTSPAGE_SMALLDESC

!define MUI_WELCOMEPAGE_TITLE "$(S_WelcomeTitle)"
!define MUI_WELCOMEPAGE_TEXT  "$(S_WelcomeText)"
!insertmacro MUI_PAGE_WELCOME

; Apache-2.0 is a grant, not a contract you are asked to sign, so this page
; informs rather than demands: the button is Next and the text says so.  What
; the user does have to see is the disclaimer, because this program sizes
; machinery and the licence is where the warranty position is stated.
!define MUI_PAGE_HEADER_TEXT        "$(S_LicHeader)"
!define MUI_PAGE_HEADER_SUBTEXT     "$(S_LicSub)"
!define MUI_LICENSEPAGE_TEXT_TOP    "$(S_LicTop)"
!define MUI_LICENSEPAGE_TEXT_BOTTOM "$(S_LicBottom)"
!define MUI_LICENSEPAGE_BUTTON      "$(^NextBtn)"
!insertmacro MUI_PAGE_LICENSE "${ROOT}\LICENSE"

!insertmacro MUI_PAGE_COMPONENTS

!define MUI_DIRECTORYPAGE_TEXT_TOP "$(S_DirTop)"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES

!define MUI_FINISHPAGE_TITLE "$(S_FinishTitle)"
!define MUI_FINISHPAGE_TEXT  "$(S_FinishText)"
; Through explorer, so the application runs with the user's own token.  Exec
; here would hand it the installer's elevated one, and an engineering tool that
; silently runs as administrator is a tool that writes its files where nobody
; expects to find them.
!define MUI_FINISHPAGE_RUN
!define MUI_FINISHPAGE_RUN_FUNCTION LaunchDeElevated
!define MUI_FINISHPAGE_RUN_TEXT "$(S_RunApp)"
!define MUI_FINISHPAGE_NOREBOOTSUPPORT
!define MUI_FINISHPAGE_LINK "$(S_SupportLink)"
!define MUI_FINISHPAGE_LINK_LOCATION "${APP_WEBSITE}"
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

; First language is the default.
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Turkish"

!define MUI_LANGDLL_REGISTRY_ROOT "HKLM"
!define MUI_LANGDLL_REGISTRY_KEY "Software\${APP_VENDOR}\${APP_NAME}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "Installer Language"

; -------------------------------------------------------------- strings ----
LangString S_AbortWarn ${LANG_ENGLISH} "Are you sure you want to quit the setup?"
LangString S_AbortWarn ${LANG_TURKISH} "Kurulumdan çıkmak istediğinize emin misiniz?"

LangString S_WelcomeTitle ${LANG_ENGLISH} "Welcome to the ${APP_NAME} ${APP_VERSION} setup"
LangString S_WelcomeTitle ${LANG_TURKISH} "${APP_NAME} ${APP_VERSION} kurulumuna hoş geldiniz"

LangString S_WelcomeText ${LANG_ENGLISH} "This will install ${APP_NAME} ${APP_VERSION} - a parametric cycloidal drive generator with engineering analysis and CAD export.$\r$\n$\r$\nIt needs about 1.5 GB of disk space, most of which is the CAD kernel that writes STEP and STL.$\r$\n$\r$\nClick Next to continue."
LangString S_WelcomeText ${LANG_TURKISH} "Bu sihirbaz ${APP_NAME} ${APP_VERSION} sürümünü kuracaktır: mühendislik analizi ve CAD çıktısı üreten parametrik sikloidal redüktör tasarım aracı.$\r$\n$\r$\nYaklaşık 1,5 GB disk alanı gerekir; bunun büyük bölümü STEP ve STL yazan CAD çekirdeğidir.$\r$\n$\r$\nDevam etmek için İleri'ye tıklayın."

LangString S_LicHeader ${LANG_ENGLISH} "Licence"
LangString S_LicHeader ${LANG_TURKISH} "Lisans"
LangString S_LicSub ${LANG_ENGLISH} "${APP_NAME} is free and open source software."
LangString S_LicSub ${LANG_TURKISH} "${APP_NAME} özgür ve açık kaynaklı bir yazılımdır."
LangString S_LicTop ${LANG_ENGLISH} "Apache License 2.0. You may use, modify and redistribute this software."
LangString S_LicTop ${LANG_TURKISH} "Apache Lisansı 2.0. Bu yazılımı kullanabilir, değiştirebilir ve yeniden dağıtabilirsiniz."
LangString S_LicBottom ${LANG_ENGLISH} "No acceptance is requested; this is shown for information. Note sections 7 and 8: the software is provided without warranty. The numbers it produces are preliminary sizing estimates, not a certification - validate against a physical prototype before anything load-bearing depends on them. Click Next to continue."
LangString S_LicBottom ${LANG_TURKISH} "Onayınız istenmez; bu metin bilgilendirme amaçlıdır. 7. ve 8. maddelere dikkat edin: yazılım garantisiz sunulur. Ürettiği sayılar ön boyutlandırma tahminleridir, sertifikasyon değildir - yük taşıyan hiçbir şey bunlara dayanmadan önce fiziksel bir prototiple doğrulayın. Devam etmek için İleri'ye tıklayın."

LangString S_DirTop ${LANG_ENGLISH} "${APP_NAME} will be installed in the folder below. Click Browse to choose a different one.$\r$\nYour designs and preferences are kept elsewhere and uninstalling leaves them untouched."
LangString S_DirTop ${LANG_TURKISH} "${APP_NAME} aşağıdaki klasöre kurulacaktır. Farklı bir klasör için Gözat'a tıklayın.$\r$\nTasarımlarınız ve tercihleriniz başka yerde saklanır; kaldırma işlemi onlara dokunmaz."

LangString S_FinishTitle ${LANG_ENGLISH} "Installation complete"
LangString S_FinishTitle ${LANG_TURKISH} "Kurulum tamamlandı"
LangString S_FinishText ${LANG_ENGLISH} "${APP_NAME} ${APP_VERSION} has been installed.$\r$\n$\r$\nLeave the box below ticked to start it now."
LangString S_FinishText ${LANG_TURKISH} "${APP_NAME} ${APP_VERSION} kuruldu.$\r$\n$\r$\nHemen başlatmak için aşağıdaki kutuyu işaretli bırakın."
LangString S_RunApp ${LANG_ENGLISH} "Start ${APP_NAME}"
LangString S_RunApp ${LANG_TURKISH} "${APP_NAME} uygulamasını başlat"
LangString S_SupportLink ${LANG_ENGLISH} "Documentation and issue tracker"
LangString S_SupportLink ${LANG_TURKISH} "Belgeler ve hata takibi"

LangString S_NeedAdmin ${LANG_ENGLISH} "Administrator rights are required to install."
LangString S_NeedAdmin ${LANG_TURKISH} "Kurulum için yönetici hakları gereklidir."
LangString S_AppRunningRetry ${LANG_ENGLISH} "${APP_NAME} appears to be running.$\n$\nClose it and click Retry."
LangString S_AppRunningRetry ${LANG_TURKISH} "${APP_NAME} çalışıyor görünüyor.$\n$\nUygulamayı kapatıp Yeniden Dene'ye tıklayın."
LangString S_RemovingOld ${LANG_ENGLISH} "Removing the previous version (v$R1)..."
LangString S_RemovingOld ${LANG_TURKISH} "Önceki sürüm kaldırılıyor (v$R1)..."
LangString S_CleanOld ${LANG_ENGLISH} "Clearing the target folder..."
LangString S_CleanOld ${LANG_TURKISH} "Hedef klasör temizleniyor..."
LangString S_Copying ${LANG_ENGLISH} "Copying files. The CAD kernel is large; this takes a minute..."
LangString S_Copying ${LANG_TURKISH} "Dosyalar kopyalanıyor. CAD çekirdeği büyüktür, bu bir dakika sürebilir..."
LangString S_WriteError ${LANG_ENGLISH} "No write permission for the installation directory: $INSTDIR"
LangString S_WriteError ${LANG_TURKISH} "Kurulum dizinine yazma izni yok: $INSTDIR"
LangString S_UninstallConfirm ${LANG_ENGLISH} "Remove ${APP_NAME}? Your saved designs and preferences are kept."
LangString S_UninstallConfirm ${LANG_TURKISH} "${APP_NAME} kaldırılsın mı? Kayıtlı tasarımlarınız ve tercihleriniz korunur."

LangString S_SecMain ${LANG_ENGLISH} "${APP_NAME} (required)"
LangString S_SecMain ${LANG_TURKISH} "${APP_NAME} (zorunlu)"
LangString S_SecStartMenu ${LANG_ENGLISH} "Start menu shortcuts"
LangString S_SecStartMenu ${LANG_TURKISH} "Başlat menüsü kısayolları"
LangString S_SecDesktop ${LANG_ENGLISH} "Desktop shortcut"
LangString S_SecDesktop ${LANG_TURKISH} "Masaüstü kısayolu"
LangString S_DescMain ${LANG_ENGLISH} "The application, the CAD kernel and everything it needs to run."
LangString S_DescMain ${LANG_TURKISH} "Uygulama, CAD çekirdeği ve çalışması için gereken her şey."
LangString S_DescStartMenu ${LANG_ENGLISH} "Adds a ${APP_NAME} group to the Start menu."
LangString S_DescStartMenu ${LANG_TURKISH} "Başlat menüsüne bir ${APP_NAME} grubu ekler."
LangString S_DescDesktop ${LANG_ENGLISH} "Places a shortcut on the desktop."
LangString S_DescDesktop ${LANG_TURKISH} "Masaüstüne bir kısayol koyar."
LangString S_LnkUninstall ${LANG_ENGLISH} "Uninstall"
LangString S_LnkUninstall ${LANG_TURKISH} "Kaldır"
LangString S_LnkWebsite ${LANG_ENGLISH} "Documentation"
LangString S_LnkWebsite ${LANG_TURKISH} "Belgeler"

; ------------------------------------------------------------- start-up ----
Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
  UserInfo::GetAccountType
  Pop $0
  ${If} $0 != "admin"
    MessageBox MB_OK|MB_ICONSTOP "$(S_NeedAdmin)"
    Quit
  ${EndIf}
  ; A previous version is not asked about here.  Upgrading is the normal case
  ; and it happens silently once the user presses Install - see SecMain.
FunctionEnd

; Whether the application is running, decided by whether its executable can be
; deleted.  A window-title search is the obvious alternative and is unreliable:
; the title carries the design, so it is never the string you looked for.
Function AssertExeClosed
  Exch $0
  ${If} ${FileExists} "$0\${EXE_NAME}"
    ${Do}
      ClearErrors
      Delete "$0\${EXE_NAME}"
      ${IfNot} ${Errors}
        ${Break}
      ${EndIf}
      MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION "$(S_AppRunningRetry)" /SD IDCANCEL IDRETRY +2
      Abort
    ${Loop}
  ${EndIf}
  Pop $0
FunctionEnd

Function LaunchDeElevated
  Exec '"$WINDIR\explorer.exe" "$INSTDIR\${EXE_NAME}"'
FunctionEnd

Function un.onInit
  !insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_YESNO|MB_ICONQUESTION "$(S_UninstallConfirm)" /SD IDYES IDYES +2
  Abort
FunctionEnd

; ------------------------------------------------------------- sections ----
Section "$(S_SecMain)" SecMain
  SectionIn RO

  ; Upgrade in place by clearing the old install first.  The previous
  ; uninstaller is deliberately not called - it can prompt even when run
  ; silently - and installing *over* a PyInstaller bundle is worse than either:
  ; leftover modules and DLLs from the old version load in preference to the
  ; new ones and fail in ways that look like a bug in the application.
  ;
  ; This has to run before SetOutPath "$INSTDIR": if the working directory is
  ; inside the folder being removed, RMDir cannot remove the folder itself.
  SetOutPath "$TEMP"
  ReadRegStr $R1 HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayVersion"
  ReadRegStr $R2 HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "InstallLocation"
  ${If} $R2 != ""
  ${AndIf} ${FileExists} "$R2\${EXE_NAME}"     ; never RMDir a path from a broken key
    DetailPrint "$(S_RemovingOld)"
    Push "$R2"
    Call AssertExeClosed
    RMDir /r "$R2"
    Delete "$DESKTOP\${APP_NAME}.lnk"
    RMDir /r "$SMPROGRAMS\${APP_NAME}"
    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}"
  ${EndIf}

  DetailPrint "$(S_CleanOld)"
  Push "$INSTDIR"
  Call AssertExeClosed

  ClearErrors
  CreateDirectory "$INSTDIR"
  IfErrors 0 +3
    MessageBox MB_OK|MB_ICONSTOP "$(S_WriteError)"
    Abort
  SetOutPath "$INSTDIR"

  DetailPrint "$(S_Copying)"
  File /r "${BUILD_DIR}\*.*"

  ; The licence and the notice travel with the installed copy.  Apache-2.0
  ; section 4 requires both to be handed on with any distribution, and this is
  ; a distribution.
  File "${ROOT}\LICENSE"
  File "${ROOT}\NOTICE"
  File "${ROOT}\README.md"
  File "${ROOT}\CHANGELOG.md"

  WriteUninstaller "$INSTDIR\uninstall.exe"

  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayName" "${APP_NAME}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayVersion" "${APP_VERSION}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "Publisher" "${APP_VENDOR}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayIcon" "$INSTDIR\${EXE_NAME}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "QuietUninstallString" '"$INSTDIR\uninstall.exe" /S'
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "URLInfoAbout" "${APP_WEBSITE}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "HelpLink" "${APP_HELPURL}"
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "NoModify" 1
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "NoRepair" 1

  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  IntFmt $0 "0x%08X" $0
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "EstimatedSize" "$0"

  WriteRegStr HKLM "Software\${APP_VENDOR}\${APP_NAME}" "Install_Dir" "$INSTDIR"
  WriteRegStr HKLM "Software\${APP_VENDOR}\${APP_NAME}" "Version" "${APP_VERSION}"
SectionEnd

Section "$(S_SecStartMenu)" SecStartMenu
  CreateDirectory "$SMPROGRAMS\${APP_NAME}"
  CreateShortcut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\${EXE_NAME}"
  CreateShortcut "$SMPROGRAMS\${APP_NAME}\$(S_LnkUninstall).lnk" "$INSTDIR\uninstall.exe"
  CreateShortcut "$SMPROGRAMS\${APP_NAME}\$(S_LnkWebsite).lnk" "${APP_WEBSITE}"
SectionEnd

Section "$(S_SecDesktop)" SecDesktop
  CreateShortcut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${EXE_NAME}"
SectionEnd

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SecMain} "$(S_DescMain)"
  !insertmacro MUI_DESCRIPTION_TEXT ${SecStartMenu} "$(S_DescStartMenu)"
  !insertmacro MUI_DESCRIPTION_TEXT ${SecDesktop} "$(S_DescDesktop)"
!insertmacro MUI_FUNCTION_DESCRIPTION_END

; ------------------------------------------------------------ uninstall ----
Section "Uninstall"
  Delete "$DESKTOP\${APP_NAME}.lnk"
  RMDir /r "$SMPROGRAMS\${APP_NAME}"
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}"
  DeleteRegKey HKLM "Software\${APP_VENDOR}\${APP_NAME}"
  RMDir /r "$INSTDIR"

  ; HKCU\Software\cycloidgen is deliberately left alone.  That is where the
  ; application's own preferences live, and among them is the design the user
  ; was last working on.  Uninstalling a program is not consent to throw away
  ; the work that was open in it, and reinstalling should find it again.
  SetAutoClose true
SectionEnd

; --------------------------------------------------------------- signing ---
; release.ps1 passes /DSIGNCMD="signtool sign ..." when a certificate is
; configured.  Both hooks matter: an unsigned uninstaller shows "Unknown
; Publisher" at the UAC prompt even when the installer itself is signed.
!ifdef SIGNCMD
  !finalize      '${SIGNCMD} "%1"'
  !uninstfinalize '${SIGNCMD} "%1"'
!endif
